name: Hijak Hawaii
favicon: null
layout_spectrum: 0.39458
typography_spectrum: 0.20961
title: HIJAK HAWAII
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ee001a'
    - '#f5faff'
    - '#1a1823'
    - '#646263'
    - '#48a0b6'
  brandStrength: 0.625
  lightness: 0.8106486045289785
  saturation: 0.125
  rhythmicContrast: 0.7027768513653427
purpose: []
