name: Hijak Hawaii
favicon: null
layout_spectrum: 0.24668933521024883
typography_spectrum: 0.8584791037719697
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9775435319170356
  lightness: 0.8106486045289785
  saturation: 0.06855021812953055
  rhythmicContrast: 0.7027768513653427
purpose: []
